### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by radusuciu** [jdrudolph/goenrich#17]
I executed the example code in the README exactly with both Entrez and Uniprot db's and in both cases encountered different errors. I am using Python 3.7 with `networkx==2.3`, since as noted in other issues networkx 2.4 does not work.

```python
>>> df = goenrich.enrich.analyze(O, query, background_attribute)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radu/miniconda3/envs/bio/lib/python3.7/site-packages/goenrich/enrich.py", line 39, in analyze
    p=ps, x=xs, n=ns, M=M, N=N)
  File "/home/radu/miniconda3/envs/bio/lib/python3.7/site-packages/goenrich/export.py", line 16, in to_frame
    names, namespaces = zip(*[(n['name'], n['namespace']) for n in nodes])
  File "/home/radu/miniconda3/envs/bio/lib/python3.7/site-packages/goenrich/export.py", line 16, in <listcomp>
    names, namespaces = zip(*[(n['name'], n['namespace']) for n in nodes])
KeyError: 'name'
```

Am I missing something? Is my version of python not supported? Thanks!

**Comment by jdrudolph** [comment]
would you mind trying with the new version 1.12. it uses `networkx >= 2.4`. If the issue persists feel free to reopen this issue.
